---
users:

  'plone':
    name: 'Plone installation'
    email: 'paulorogerio@uft.edu.br'
    public_keys:
      - 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDArI6K07GugvbXdcIS0thjd105Xfp+7nL24tt4YKCgCdEe2zn7VsOQEYTdvX5T0nRPw28bj7hrltLepGq7xntABj5crNUog+A40eC1xwY2MSwPDKyJjqCy4ZPupCz3i4GOBSTQHEE+Cfg8Sj0lGlBGqLXMW1FJZNUjYfmGqGgwwO9RbahIgYNxO7Ue5+2nVMsmMEHsGsHXk29mQQPyH4eFpb5yWLudNhis6b8kiK6JZSsPbIigPIHZj7Z+XXO/skC1UXsc43gtUxlT5+bIfz2ySKTMhBUFne+mTFvkgukJlhly5lFYHT+ram2twaYGIp10gA/7E5EjecZG8aS2BEzKGxLkx2diH3xajIhKjQjpQ/qfIvuLpspZlYaQOtaQwaP3TVngdQebGJ3jtuMGGrAwU6PTL4T/ITlF35YF54PWpa5hvb1tgGb1BZ8mUWpQmcxMKfzS+PIo+hxsQLH4J5+E03yjH4r+ImAnk1/MuMD/05dj9i85EkDIi7oE78IBtKkoVBJ6OJm92cdEOM0BOsaa8oButOPmT++QhDwJe3khSI94rEmbzoe0Dqd1qvTiLEqjT4xVbb4xscKFxzZpu+JUNVXegLZu2g3yhvK5kV9Uk49mpxgH8ctb0vL9no/zyK6UKecEKuEvKk1Ah9Nd+uas16CFEAI8zWZCCASlX2JZXQ== paulorogerio.to@gmail.com'
    password: '$6$8TrTq/2twy7u./bS$5gxT7m93.aVJD1P9V0y.EMcCvgH2RV8pM4vVyGFpqx3zEPUvmib7nQtJD6vxJRTMyR9oPRi323tbwpx0wLyWs.'
    state: present
    shell: '/bin/bash'
    groups:
      - 'docker'
      - 'plone'
